### ISSUE TITLE
keyboard doesnt show in landscape

### ISSUE THREAD

**Issue by futrDevelopment** [scoute-dich/browser#12]
I'm new to GitHub so I don't know what the hell I'm doing.  but i;ve been playing around with the source code and got the keyboard to show in landscape but it wasn't showing before. also I put adblock and a request desktop that works in and removed a few things too.  My question is is that ok? I mean can I continue developing my own version of this or am I supposed to not do that?  I just don't want to do the wrong thing.

**Comment by scoute-dich** [comment]
You can develop your own version, since my app is licensed under GPL. But you must license your modified work under the same license. If you want to publish your fork you must also publish the source code. This is the right way if you want to go in an other direction than I go.

An other possibility is to contribute on my work. You can send pull requests, which I can implement in my app.

For example I would like to know, how you solved the keyboard bug and how you integrated the "request desktop" feature. There is an issue #9 and really want to fix that. So if you have the solution it would be nice to share.

**Comment by futrDevelopment** [comment]
I want to do this the right way.   I will be more than happy to go to the original version I have and add the same modifications I have on my version which is much reduced because I didn't want to use so much of your code since I want to have fun coming up with my own, but the keyboard issue was a matter of changing the showKeyboard() in helper_editText InputMethodManager from SHOW_IMPLICIT to SHOW_FORCED, and then for the request desktop I created a MyUserAgent class that handles getting the default user agent (which is the mobile agent) and defining a modern desktop agent (which I obtained by choosing "request desktop" in chrome and going to whatsmyuseragent.com (I think that was the site) and copying the user agent it gave me into the class as the agent to show.  

Then, since it wouldn't work all the time I figured it was due to the site already having me in an anonymous session cookie so I incorporated a delete cookie by url method which wipes the session cookie for the current site before requesting the other mode.  Its all in a crude switch right now, triggered by tapping the toolbar and it comes up in an alert, but I will add it to your javascript toggle dialog along with the adblock feature if you want.
  
I am looking pretty hard at a really good tab resource and I think i'm going to try to get some tabs into this magnificent browser.  Let me know if you would like me to do otherwise, I will respect your wishes as the original creator.

**Comment by scoute-dich** [comment]
Thanks for the tip with the keyboard. I fixed it. But I'm still not able to force desktop view... :-(
I also found no solutions until now to implement tabs.

As said before: you can do what you want with my code:

- copy it
- share it
- modify it

The only thing you **MUST** do is to license it under GPL, so that others also can use your modified code. That's the sense of Open Source and free software. One community to help each other.

If you want to contribute, make pull requests to improve my browser. ;-)

**Comment by rjc** [comment]
Just a quick clarification as the OP might not be familiar with alternatives - that's **not** the sense of open source or free software, at least not entirely.

That's what copyleft licenses (mainly `GPL`) require one to do. Let's not forget that a large portion of open source/free software ecosystem uses permissive licenses (`BSD`, `ISC`, `MIT`/`X11`, etc.) which grant more of the same rights to all of the users of said software not just the original author who, under the terms of the `GPL`, retains more rights than if it was an `ISC`-licenses software.

The above does not obviously apply here as your browser is `GPL`-licensed but it fees like more explanation was required - especially since your web browsers itself uses components under permissive licenses, i.e. [Apache](https://github.com/ksoichiro/Android-ObservableScrollView/blob/master/LICENSE.txt) or [MIT-style](https://github.com/sveinungkb/encrypted-userprefs/blob/master/src/SecurePreferences.java). I couldn't determine the license of the original [`browser`](https://github.com/yoshihiroando/browser) as it doesn't seem to present anywhere in its repository.

**Comment by futrDevelopment** [comment]
I will update my fork with the new useragent and adblock features, and when I do implement tabs I will come back to this fork and update it with the tabs too.  The work you have contributed to this browser has helped me tremendously to get a solid, opensource headstart on a simple, specialized browser which will not be my main project but has still had the benefit of being tested in the field.  Feeling like I made a meaningful contribution to that makes making my little downsized version of it feel ok.  I always want people to feel better off for any exchange I make with them.

Speaking of that, there is one question I would really like to ask you about how you got the videos to work so well in fullscreen.  If you could answer that question for me, I could roll my own browser (I would still make the small opensource browser for now because I still need a quick simple browser) and really take my time creating my own major browser project from scratch later.   Its just that I haven't been able to find out from anyone who knows how yet so this one was working already and that's why I chose it as a starting point.  I can give you my email address if you prefer to contact me directly.

thanks rjc for the clarification, I was under the impression that scoute-dich was the original creator of this project.  what alternatives are you referring to though? I haven't seen another browser project that handles fullscreen video as elegantly with out having just way too much code I don't need or want under a more permissive licence.  But I really do appreciate the clarification.

**Comment by futrDevelopment** [comment]
aaand done.  You can go to yahoo.com and request desktop and switch on adblock and you will see the desktop site and a big missing area to the top right where the ad is supposed to be.  Remember that some sites such as GitHub go by the dimensions of your screen and not your mobile agent so those sites will hold onto the mobile configuration for dear life. but browsing with request desktop on will give you the mobile site unless the site is dead set on not doing so.

I work all day so I hardly ever have time to code right now but ill get on those tabs after I accomplish what is necessary next week.

please think about sending me that email I would really like to know how to make the videos play fullscreen so I can roll my own browser from the ground up.

also, I commented it and left you to have fun implementing it into the right browser as well, and making it so request desktop preference is recognized right at startup.

**Comment by scoute-dich** [comment]
@rjc also thanks for clarification.
@futrDevelopment : 

I think I have implemented your pull reqest the right way now. I will test it the next days and then push my changes back to the repo. Thanks for your great help. That's a kind of work which I couldn't do. I haven't learned programming. I just started with some basic tutorials. Whenever I have a problem I search on stackoverflow or github for a solution. I will also name you in the "About section" for your help, if this is ok for you.

The solution for implementing the fullscreen video was also anywhere on stackoverflow (of course I can't find the right link now again...). The trick was the Frame_layout in "activity_browser.xml" and the handling of the custom view container in the "private class myWebChromeClient extends WebChromeClient" in the Browser activities. If you have more questions concerning this, you can ask me.

Regards
Gaukler Faun

**Comment by futrDevelopment** [comment]
awesome.  thx for pointing me in the right direction.  hey don't downplay stackoverflow it is the main reason for the cookie method being available to me when I needed it.  stackoverflow is like everyone's overexperienced buddy who's had the exact same error you're having time and time again and knows exactly how to fix it almost every time.  it's like having a pocket mechanic lol.  I'll have fun exploring the webchromeclient and if I cant figure it out ill shoot u an email.  till then If and when I put tabs in my specialized version I will put tabs into your browser, just if you mention me plz mention me as cgslurp LLC,  I am always happy to help a fellow programmer of any level, and am always appreciative of other programmers who are similar to myself and cool with helping a programmer of my level.  Best of luck and ill bb to throw u some tabs most likely!

**Comment by scoute-dich** [comment]
Ok. Update is on his way... See you again one time...
And again: thanks for contributing.
