### ISSUE TITLE
Visiting URLs with "umlaute" not possible (may also affect other special characters)

### ISSUE THREAD

**Issue by GerRudi** [scoute-dich/browser#155]
When I type in the URL "allestörungen.de" (or other ones with ä,ö,ü), it'll simply start a search request instead of visiting the page.

**Comment by BO41** [comment]
I can confirm this behavior.

Where in the code is this handled?

**Comment by scoute-dich** [comment]
It's handled in the Browser.unit file. I added exception for "ö,ä,ü". See latest commit.

**Comment by BO41** [comment]
This issue should be fixed in the newest version right?

If you open an URL with named characters, the page will be opened. But the URL looks completely wrong. (Should be allestörungen.de)

![screenshot_20180831-120628](https://user-images.githubusercontent.com/29450609/44906971-bad1d680-ad16-11e8-89ac-d160da677710.png)

and searching for something containing named characters, for example "tür" (german for door), makes something strange.
And it is not a problem of my [default search engine](duckduckgo.com). (should be https://duckduckgo.com/?q=t%C3%BCr&t=hi&ia=web)

![screenshot_20180831-120650](https://user-images.githubusercontent.com/29450609/44907041-f9679100-ad16-11e8-9de3-c64640bd1687.png)


I am pretty sure it is not a problem of my setup/smartphone.
I don't know what people were thinking when allowing such characters in urls :man_facepalming:

**Comment by BO41** [comment]
@scoute-dich do you want to reopen this issue or should I open up a new one?

**Comment by scoute-dich** [comment]
Bevore I close it again. Here's a test apk. On my side loading and searching urls with "Umlaute" should work now. Just rename zip -> apk

[app-debug.zip](https://github.com/scoute-dich/browser/files/2384920/app-debug.zip)

**Comment by BO41** [comment]
@scoute-dich can confirm, issue is resolved :muscle: 

about the strange looking urls, I think it is okay to let them look life they do (www.xn--80ak6aa92e.com/) but it would be good to have a popup which informs the user about the Punycode phishing attack. Otherwise you will get more issues created.
or just leave it as it is :)

**Comment by scoute-dich** [comment]
I'll lwve it as it is.
