### ISSUE TITLE
Large browser fingerprint

### ISSUE THREAD

**Issue by e3b** [scoute-dich/browser#18]
The large fingerprint of Browser (run the test on <https://panopticlick.eff.org>) does not offer good tracking protection.

It would be nice if there was also the option of choosing a more common user agent (like one can choose between a desktop or mobile user agent now) as well as a possibility to use the same HTTP_accept headers as Tor Browser.

I don't know how easy it is to do anything with the canvas and WebGL fingerprint hashes. Brave's [Fingerprinting Protection Mode](https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode) might be helpful.

**Comment by tclaybor** [comment]
Hi, my results of that same site were as follows.

Is your browser blocking tracking ads?         ✓
Is your browser blocking invisible trackers? ✓
Allows 3rd parties that honor DoNotTrack? ✗
Protect from fingerprinting?                           ✗

I consider #3 a good thing, even though that site does not. Therefore the app is blocking 

- Tracking Add
- Invisible Trackers
- Most other Ads
- Cookies (3rd party by default, all optional)

That's pretty good for such a light browser app. Especially since the Dev mentioned they are new to this and learning as they go. 

"Browser fingerprinting is both difficult to detect and and extremely difficult to thwart." Pulled from the site you linked. Also from your link

"Disabling JavaScript is a powerful defense against browser fingerprinting, because it cuts off the methods that websites can use to detect plugins and fonts, as well as preventing the use of most kinds of supercookie. Unfortunately, JavaScript is necessary to make a lot of sites work well."

This browser implements a JavaScript Whitelist, which adds another 'point' for this browser. Disable it by default and add sites to your whitelist as you go. 

I empathize with your concerns posted, but the features I highlighted above will most likely protect you from 95% or more of fingerprinting.

Additionally, you might try BlockThis! for Android
https://block-this.com/
It works by creating a (100% LOCAL) VPN that directs all ad traffic to 127.0.0.1. I've used it with great success (although I currently use AdHell for Samsung). BlockThis! is 100% free, open source, and highly configurable. It works system-wide by default, but can be configured to whitelist apps.

_________________________________________________

To the developer:

Here is some info that might help address the points this bug report mentions.

Do Not Track is a simple header indicating that you don't want to be tracked. Because it is a header, not a cookie, users can clear cookies without disrupting the functionality of the Do Not Track flag. Unfortunately, most websites and online trackers currently ignore the Do Not Track signal.

Browser fingerprinting is a method of tracking internet users. There are defensive measures that can be taken, but none are ideal. In practice, the most realistic protection is using Tor Browser, which has put a lot of effort into reducing browser fingerprintability. For day-to-day use, the best options are tools like Privacy Badger or Disconnect that will block the domains that try to perform fingerprinting, and/or to use a tool like NoScript for Firefox, which greatly reduces the amount of data available to fingerprinters.

Cheers!

**Comment by scoute-dich** [comment]
I thought a little about the said things:

I will not implement tor support. I also used tor but using tor means to lose performance. Also the normal user don't need it and my browser should be lightweight. Adblocking, cookie and JavaScript settings should be enough to protect privacy for normal users. All others can use a browser with tor support. I think what @tclaybor said would be the right way.

Keep it as simple and clean as possible.
