### ISSUE TITLE
Typed text on address bar not visible on Blackberry Keyone

### ISSUE THREAD

**Issue by vani77a** [scoute-dich/browser#225]
When selecting text on the address bar, highlighted text not visible, title on it is static, no change, even when text is selected. I can enter text though, as I tried to long-press and select-all-text and replaced it with "google.com" and press enter, and it will send me to google. The title on the bar will then be changed into "googlemcom at duckduckgo"

**Comment by gutyo** [comment]
I have the same problem on Blackberry Key2 on Android 8.1.0 (after last update)

**Comment by scoute-dich** [comment]
Is the title still of the website still visible?

**Comment by tusch001** [comment]
The same happens, if I switch the focus to a diiferent app. When I come back and the last visited tab on top had a pdf-Link for download opened, the input of a new webpage restarts the pdf-download but doesn't open the link to the new webpage. Link text is also not visible, Only way to solve this is to clise the active tab and open a new tab.

Android 6.0.1
Browser 5.9, 6.0, and 6.2 (I never tested it in 6.1 / 6.1.1)

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/2787516/app-debug.apk.zip)
Will this solve the issue? Can someone please test it? Just rename  file to "app-debug.apk".

**Comment by Tobiplayer3** [comment]
1. Is the page that is opening automatically the project's github page? If that's the case, it's the default start page. You can change the start page in the bookmarks panel.
2. What exactly do you mean when you say it doesn't ask you to load bookmarks and history? Bookmarks and history can be found with the button on the left side of the URL bar, is this item gone?
3. There is no need for an OK button when changing these options because it should be saved automatically when you select an option.

**Comment by tusch001** [comment]
@Tobiplayer3
@1 and 2: I didn't realize, the homepage is set to github, I started the same page from the github email on the first start. My standard settings start with the list of bookmarks and I have never used a webpage for first view. Likewise I am so used to see my list of bookmarks when opening a new tab that I forgot that you can reach this with the left button in the toolbar. And with the new images on top of this list (version 6.2) everything looked so different. Sorry, my mistake.
@3: this is a good way to apply changes. I'm still using older Android versions and was looking for the ok button. 
Now saving the settings works fine. I just remember (at the beginning of my testing) that I had seen the navigation button floating around after going through the settings. Not any more. Maybe I hit cancel instead of going back? In case this happens again I let you know.

Summary: everything is fine.

Thanks for doing all the good work.

**Comment by tusch001** [comment]
@Tobiplayer3 - Update @3, concerning the settings with the navigation button.
Old: toolbar always visible, navigation button always hidden.
New: I changed the guestures for the navigation button to try them out. Changed the navigation button to always visible --> not visible. After opening the settings the menu highlights always visible. Even after exiting and restarting the browser no floating navigation button.

**Comment by scoute-dich** [comment]
The original issue was about "address bar not visible" on some phones. Please open an other issue for other problems.

So again the question n is the original issue solved? I don't have a BlackBerry phone to test.

**Comment by vani77a** [comment]
@scoute-ditch
I just tested the apk on my Keyone, the address bar still don't change. I have screen capture video if you  could want to see, I can send it to you.

**Comment by scoute-dich** [comment]
Are all these phones with keyboard on screen? Or do they have a "separated" keyboard?

**Comment by scoute-dich** [comment]
Ok. I see. I'll look that was the only explanation. Didn't thought about that. I'll see what I can do.

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/2799489/app-debug.apk.zip)
Ok, here is something to test. I assume that an issue will be, that adressbar will stay visible, until you touch outside. But test it ...

**Comment by Vistaus** [comment]
Same problem on my KEY2. Will test the APK in the post above and report back.

**Comment by Vistaus** [comment]
@scoute-dich That does not solve the issue. Text remains visible in the address bar with no way to input a URL.

**Comment by Vistaus** [comment]
> [app-debug.apk.zip](https://github.com/scoute-dich/browser/files/2799489/app-debug.apk.zip)
> Ok, here is something to test. I assume that an issue will be, that adressbar will stay visible, until you touch outside. But test it ...

That does not solve the issue. Text remains visible in the address bar with no way to input a URL.

It's a very odd issue as no other browser has this issue on my KEY2.

**Comment by scoute-dich** [comment]
Thanks for testing. At the moment I've now more idea how to solve this issue. But I'll try it.

**Comment by Vistaus** [comment]
> Thanks for testing. At the moment I've now more idea how to solve this issue. But I'll try it.

And thank *you* for looking into it! Like I said: it's very strange that this is the only browser that even has this issue; all other browsers work as expected on my KEY2.

**Comment by scoute-dich** [comment]
Something new to test for BlackBerry users:

https://forum.xda-developers.com/android/apps-games/app-browser-t3500091/post79402038

I'm on mobile and can't figure out how to attach files. So that's the link to the xda thread, where I uploaded the apk.

**Comment by Vistaus** [comment]
That APK fixes it. Thank you so much! :)

**Comment by scoute-dich** [comment]
Real? That's great. I'll release the next update soon!
