### ISSUE TITLE
[feature request] Dynamic bookmark

### ISSUE THREAD

**Issue by shubhiD** [scoute-dich/browser#24]
Is it possible to implement dynamic bookmark like url for the bookmark should update to last link visited on that particular website?

**Comment by tclaybor** [comment]
@shubbiD This is not directly possible while preserving privacy and protecting users. You're basically suggesting that the browser store a cookie that tracks the user's navigation habits. This is a huge no-no since the browser would have to track/record/listen to what your browsing habits are on said site. Though I am curious as to HOW or why you would use this feature, would you mind sharing? Haha

@scoute-dich This one can also be closed, as it would violate privacy and performance on said site would almost certainly take a hit.

**Comment by tclaybor** [comment]
@shubhiD re-tag since I spelled your handle wrong above... Sorry!

**Comment by shubhiD** [comment]
@tclaybor thanks for the awesome reply, well my need to have dynamic bookmark was that there is a site I particularly visit geeksforgeeks.com and they have so much content so I wanted that when I am done with one link it should update in the bookmark so it would be easy for me to reach the last content I read.

Also there are some online books and I thought It would be pretty cool If last read location would be automatically updated.

Thanks for letting me know and no need to say sorry for misspelling my handle. Thanks!

**Comment by tclaybor** [comment]
@shubhiD no problem. Happy to help. That's a great idea, but if you really think about it, when you're reading a book.. you still gotta move your book mark every time, am I right? XD

Say, if you wouldn't mind closing this issue, since it can't really go anywhere from here? I would do it if I could, but only you or the Dev can. :)

**Comment by shubhiD** [comment]
@tclaybor  Sure, just wanted to get insights on this feature, thanks for your time
