### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shailandraRajput** [scoute-dich/browser#27]
Hello,
This Browser Is Crash in Bookmark Section When Tap on Toolbar.
And Can You Add Night mode In Browser.
and A user can save bookmark On browsers homescreen. 
and remove github page and Use a static home page like other browser
or add Inbuilt Download manager
Thanks

**Comment by tclaybor** [comment]
Hi there. I'm just a user of this app, but I would like to say a few things in response to your issue. Please keep in mind I say the below in a friendly manor and mean no disrespect to you.

1. Yes, that bug is replicable on both the Bookmark and ReadLater screens. It occurs when tapping on the bar (same area as search on v3.8+) or swiping on the bar. I stumbled across it when I tried to swipe to return to my browsing page... Not sure why I tried to do it that way, it just felt instinctual to do so.

Please create a feature request for the rest of your points, they are not bugs. However, I will touch on them.

2. Night mode would be nice, but I personally spend 95% of my time in this app on a Web page, which would be unaffected. To Shailendra, keep in mind the navigation/menu bar would not change colour due to night mode, only the settings, lists, and history menus. I believe the reasoning for the colouring of the navigation/menu bar was mentioned in another issue that has been marked as closed. There are only 6, otherwise I would link it for you.

3. You're basically describing a "Speed Dial" or "Quick Access" shortcut. Given the abilities to "Read Later", "Bookmark", and "Add to homescreen", why do you want ANOTHER location to store and possibly lose links? "Add to homescreen" is both faster and more convenient than what you're asking for. Just make a folder on your phone's homescreen called "Speed Dial" and put them all there. That would be better than bloating the app. Agreed?

4. The github home screen is to support the developer. It's actually the most brilliant advertising method I've seen for a developer to promote their app. Again, add your preferred homepage to your phone's homescreen and click that to "change the homepage". The developer is nice enough to make this app ad-free, tiny, beautiful, packed full of features, open source (read: secure and privacy conscious), and above all else FREE. Try to meet the dev half way on some of these things. 

5. I believe Android Webview leverages your phone's native download manager when you download something. Therefore, adding a built-in manager would add unecessary bloat to the app. Even if it was added, it would probably just be reading a list of downloaded items from your native manager. Basically, the way it is now is the fastest and safest way it could be done.

To the developer: Thank you for the awesome app! You have my full support, and I hope you keep up the awesome work! You're the bee's knees :)

**Comment by shailandraRajput** [comment]
Thanks I'm understand this

**Comment by tclaybor** [comment]
Hey don't close this, the bug still hasn't been fixed! Haha

**Comment by shailandraRajput** [comment]
Oh yes ha ha

**Comment by tclaybor** [comment]
@shailandraRajput what version of Browser (this app) are you using?

I just realized that a download manager was implemented in version 3.8 of the app, making number 5 in my list pointless.

**Comment by shailandraRajput** [comment]
Im using 3.8.1

**Comment by tclaybor** [comment]
Okay.

1. Click the ellipses on the right side of the omnibar. (The three vertical dots)
2. Click "Open"
3. Click "Open Download Folder"

You can also open, rename, and delete files there.

**Comment by tclaybor** [comment]
@scoute-dich just reporting in that the originally mentioned issue that causes crashes occurs on all lists when the omnibar is tapped or swiped:

- PassStorage
- History
- ReadLater
- Bookmarks
- Downloads

**Comment by scoute-dich** [comment]
> This Browser Is Crash in Bookmark Section When Tap on Toolbar.

The issue will be closed in next release (which can take a few days).

> And Can You Add Night mode In Browser.

This will not be implemented.

> and A user can save bookmark On browsers homescreen and remove github page and Use a static home page like other browser

You can set your personal favorite as startpage by clicking the star in the bookmark list. Or you can set a blank page by clicking the menu in the bookmark list. In the next release there will be also the possibility to set bookmark, readLater or history as startpage. I think this will be enough.

> or add Inbuilt Download manager

This is not necessary android download manager does the job. As mentioned, you have an build in file manager, to browse downloaded files.
