### ISSUE TITLE
Bug: Pages partially blurry until scrolled

### ISSUE THREAD

**Issue by orwell96** [scoute-dich/browser#291]
System: Samsung, Android 7.7.1

In some occasions, after a webpage has fully loaded, not all parts of it or even the full page are shown blurry. This blurriness goes away after the page is scrolled once, or when switching tabs.

If the page is too short to be scrolled, it can only be "unblurred" by switching tabs.
![20190712_134422](https://user-images.githubusercontent.com/13201701/61126081-d3208f00-a4ab-11e9-9bf2-23a9953d87e6.jpg)

**Comment by scoute-dich** [comment]
Is this issue still from relevance?

**Comment by tusch001** [comment]
I've encountered it twice today (version 6.6.1). But I can't reproduce it reliably.

**Comment by scoute-dich** [comment]
I'm encountering this also sometimes. Especially pictures are often blurred. Reloading the website also solves the problem.
I think some pages are preloading their content. I found no possibility until now to solve that.

**Comment by tusch001** [comment]
These few partially blurred pages are rare. I "think" (but don't know) that happens when a connection is very slow and the page hasn't fully loaded and somehow never finishes loading the page (eg Javascript or maybe some font files still missing). Since reloading the page solves this - not a problem. I suggest that you just ignore it. I don't think it's worth your time.

Today I encountered also a partially cut page. I don't know if it's related. It happened on Android 7.1 (Lineage 14). Neither on Android 5 or 6 had difficulties displaying the page. It was while viewing code here on github. A java file with approx. 130 lines was cut around line 100 - not between lines, the rendered output in the scrollable field was suddenly at end, horizontally cut in the middle of a line. When scrolling further just white space. But in this case reloading the page didb't help (still something cached?)
Maybe a problem on "older" devices when webview is not up to date? 
Also at the moment too rare to be an issue.

**Comment by scoute-dich** [comment]
Please feel free to reopen if the problem still persists on latest version, with latest webview.
