### ISSUE TITLE
Feature Request: Intro/Tutorial Screens

### ISSUE THREAD

**Issue by tclaybor** [scoute-dich/browser#33]
It would be helpful to add a slide during the tutorial that showed or told the user how to add sites to the JavaScript Whitelist. Currently the user must have the JavaScript setting turned off, stumble upon the X icon, click it, then notice the changes on the site. It is somewhat ambiguous to less savvy users.

**Comment by scoute-dich** [comment]
OK. There is a help dialog in settings -> about. But I think this should be in a place where it is more findable. I must think of a proper solution. At the moment I must fix a few bugs, because of implementation of fragments instead of activities.

But anyway thanks for all your testing and reporting. ;-)

**Comment by scoute-dich** [comment]
I've implemented a new help dialog in menu -> more -> help. I'll do some tests the next days and then release the update.
