### ISSUE TITLE
feathure request: homepage setup, js whitelist url edit, refresh button

### ISSUE THREAD

**Issue by larryduke** [scoute-dich/browser#34]
I used aosp browser many years before android 7,  very happy to find this project. 
wish these feathures be added in the futhure.
1.  homepage setup

 2. js whitelist url edit

 3. refresh button, pull down or long press history button

**Comment by scoute-dich** [comment]
1. In next release you can set favorite startsite from bookmarklist or as an emty page over the bookmarklist menu. You can also set bookmarklist, readLater or history as startpage.

2. I'll see. Perhaps in the future.

3. Longpress history to reload will be implemented.

**Comment by scoute-dich** [comment]
Editing whitelist will not be implemented. You can backup the whitelist as textfile to sdcard, than edit it and finally restore the edited file.

The two other points are already implemented. But due to big changes in the code and some other outstanding issues it will take a while for the next update.

Regards
Gaukler Faun
