### ISSUE TITLE
[Feature Request] Default Search Engine | Google

### ISSUE THREAD

**Issue by tclaybor** [scoute-dich/browser#36]
Hello again!

Been trying to reach you via XMPP, just FYI :)

When searching from the omnibar, if the following are true:

1. Has Google set as default search engine.
-or-
2. Using "quick search" with the Google flag (.G)

The search results page will display/list Google AMP links. I know this is nitpicky, but I'm almost certain everyone hates AMP links because they alter the page URI, address bar, etc. 

For instance, linking to the URL in the omnibar while on an AMP page, the link that is copied from the omnibar will be opened as suspicious activity (Google page says this, not browser or modem).

This can be circumvented by using 

https://encrypted.google.com/search?q=%s

As the search engine string instead of the default. The results of the search will not display any AMP links.

I know AMP links are allegedly faster, but this browser is already so fast, that I don't believe it will slow anything down. Plus only a random irregular number of results are AMP anyway.

Let me know your thoughts. Thanks again for this app. You are awesome!

**Comment by tclaybor** [comment]
Update: the "suspicious activity" trigger links I'm referring to are like this:

https://www.google.com/amp/www.techrepublic.com/google-amp/article/how-to-scan-documents-directly-to-google-drive/

Sometimes they open fine when shared, other times not so much.

**Comment by scoute-dich** [comment]
For me that's no problem. I even didn't know that AMP links exist. So, when the only thing I have to do is replace the Google search string with tour suggested string, I can do that.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tclaybor** [comment]
That's great of you. I'm not sure how you keep up your good attitude with all these apps, but it's definitely an admirable quality in a developer. 

As always, thank you so much :-)

**Comment by tclaybor** [comment]
P.S. You may consider turning off your signature in FastHub, just in case you didn't realize it was there.

**Comment by scoute-dich** [comment]
This will be fixed in next update. I'll keep the signature. Fasthub is a good open source app and the OnePlus One still a good phone.

I'm not a real good developer. I just want that apps work the way I want. And of there is no app which matches my wanting, then I must write my own. And all my apps are open source, because I also use open source where it is possible (Linux rocks!). And that's my way to give something back to the community. At the moment I have vacations and a bit more time to get things organized. But there will be bader times in a few weeks...

And an other great point of open source are people like you, which report bugs, feature requests and so on. So good apps became better. Keep up your work!

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
Since your solution only works for "Google.com" and not for "Google.de" I now added "Google encrypted" as separate search site. ;-)

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
