### ISSUE TITLE
Some broken tab behaviors

### ISSUE THREAD

**Issue by firecat53** [scoute-dich/browser#40]
1. Open a URL in the first tab. Open another URL in the second tab. Now if you long press the bottom bar to get the tab list and use the red X to close the second tab, it will open the 'browser' page on Github. In my opinion this should default to either a blank page or whatever your startup page selection is (e.g. the 'bookmarks' list).

2. After opening several tabs, the current tab URL is not always correctly populated when you tap the bottom bar. It again often fills in the 'browser' Github page URL instead.

**Comment by scoute-dich** [comment]
It seems to be fixed with latest commit, but I want to test one or two days before releasing an update. Thanks again for reporting the issue. Without people like you the app wouldn't be what it now is. A lot of issues wouldn't be recognized by me...

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by firecat53** [comment]
No worries! I'd be happy to test another debug build if you want to email it.

**Comment by scoute-dich** [comment]
Sorry for the late reply. I had to do in the last few days... So, I think this will be fixed with version 4.4. If there are any further issues, fell free to open an new one. Thanks again for the input. ;-)

**Comment by firecat53** [comment]
Cool, any guess on when 4.4 will be on F-droid? Thanks!

**Comment by scoute-dich** [comment]
Normally it takes a few days... Sometimes even up to a week... You can also download latest version on PlayStore: https://play.google.com/store/apps/details?id=de.baumann.browser1

I recommend to backup your databases if you switch to PlayStore version.
