### ISSUE TITLE
adjust download directory for browser backup for google app

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#421]
Hi!
The backup directory for the fdroid apk is 
`Android/data/de.baumann.browser/files/backup_browser`.

You might want to correct the text in settings (for export browser data) for the google apk to`Android/data/de.baumann.browser1/files/browser_backup`. I guess the google playstore users are less savvy about apk naming rules:-)

Btw thanks for update 7.1. Love the individual remote load setting.

**Comment by 5c0tt-b0t** [comment]
I love this browser!
Unfortunately, I am unable to build from source (ancient PC) and the last two releases are source only.
Would one of you be kind enough to attach the .apk file here as a .zip file please?
Sorry to hijack the issue here, I dont want to open an issue requesting "provide apk files with releases" (hopefully, you will start doing this again)
Thank you!

**Comment by tusch001** [comment]
@5c0tt-b0t : I would suggest to open a new issue (I support your suggestion). Otherwise your request is probably overlooked.

**Comment by scoute-dich** [comment]
Thanks for the hint. but I will not change the strings because of such a small issue. Last time I changed strings all translations on crwodin get messed up.
