### ISSUE TITLE
List Black for Java

### ISSUE THREAD

**Issue by willf444** [scoute-dich/browser#470]
Hi!
Why not create a blacklist for Java?
It is easier to block some and leave them all released by default.

**Comment by scoute-dich** [comment]
Because the intention is to disable JavaScript by default for me. Most websites are showing their content with JavaScript disabled. The sites I visit regularly get white-listed.

With next update there will be the possibility to reload the website with JavaScript with one click from the fast-toggle-dialog.

**Comment by willf444** [comment]
What is convenient for you is not for me. It would be much easier for me to
block just a few sites and leave the rest free.

Em qui, 8 de abr de 2021 03:33, Gaukler Faun ***@***.***>
escreveu:
