### ISSUE TITLE
Long press on the bottom bar

### ISSUE THREAD

**Issue by smichel17** [scoute-dich/browser#5]
I don't really understand why the app closes with a long press on the bottom bar. Why not just by hitting back or home like every other app?

Intuitively, I would expect long pressing to copy the current url to the clipboard or something like that.

**Comment by scoute-dich** [comment]
Of you press back the last website loads. Of there is no more website in the history the next back click will trigger a snackbar message to close the app. So this is the expected behavior.

Long press to exit is to leave the app immediately. It's a fast alternative to swipe up on the toolbar to leave the app. But I can also remove it, when it's better for usability...

**Comment by scoute-dich** [comment]
I've removed it.
