### ISSUE TITLE
Does not support half screen navigation

### ISSUE THREAD

**Issue by mark-karrica** [scoute-dich/browser#612]
The browser can't work in "split screen mode". It can be a useful feature that can allow the user to chat and navigate at the same time.

**Comment by scoute-dich** [comment]
Hi,

I removed this, because there were troubles concerning the toolbar, when trying to input something (or something similar). If you want, I can enable this feature and give you a debug-apk to test.

Then, if there are problems, you can report them here, and I'll try to fix them. If I can't resolve them, the feature remains removed. If there are no problems, we can add this feature.
