### ISSUE TITLE
java.lang.NullPointerException 	at android.net.WebAddress.<init>

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#643]
java.lang.NullPointerException
	at android.net.WebAddress.<init>(WebAddress.java:66)
	at Fn.a(chromium-SystemWebViewGoogle.aab-stable-447216401:1)
	at Fn.getCookie(chromium-SystemWebViewGoogle.aab-stable-447216401:1)
	at de.baumann.browser.view.NinjaWebView.initPreferences(NinjaWebView.java:149)
	at de.baumann.browser.activity.BrowserActivity.lambda$showOverflow$64$BrowserActivity(BrowserActivity.java:1584)
	at de.baumann.browser.activity.-$$Lambda$BrowserActivity$EjW9IImEDrfTAQrwkpqNBFHeLoc.onClick(lambda)
	at android.view.View.performClick(View.java:4756)
	at android.view.View$PerformClick.run(View.java:19761)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5264)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

**Comment by scoute-dich** [comment]
Can you give the steps to reproduce this issue?

**Comment by woheller69** [comment]
maybe url is null also here.

     manager.getCookie(url)            (in NinjaWebView)

probably called from here in BrowserActivity:

        ImageButton overflow_reload = dialogView.findViewById(R.id.overflow_reload);
        overflow_reload.setOnClickListener(v -> {
            dialog_overflow.cancel();
            ninjaWebView.initPreferences(ninjaWebView.getUrl());
            ninjaWebView.reload();

Maybe exit setOnClickListener if getUrl()==null  ?

Did it happen when pressing reload?
        });

**Comment by woheller69** [comment]
getUrl() may return null, if no page has been loaded. So wherever we use getUrl() we need to make sure that "null" does not lead to problems...


<h3 class="api-name" id="getUrl()" data-text="getUrl" role="presentation" style="box-sizing: inherit; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: ; font-variant-east-asian: ; font-weight: ; font-stretch: ; font-size: ; line-height: ; font-family: ; letter-spacing: normal; margin-top: 60px; margin-right: -40px; margin-bottom: ; margin-left: ; overflow: hidden; text-overflow: ellipsis; padding-right: 40px; color: rgb(32, 33, 36); orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="devsite-heading" role="heading" aria-level="3" style="box-sizing: inherit;">getUrl</span><button type="button" class="devsite-heading-link button-flat material-icons" aria-label="Link zu diesem Abschnitt kopieren: getUrl" data-title="Link zu diesem Abschnitt kopieren: getUrl" data-id="getUrl()" style="box-sizing: border-box; appearance: none; background: 0px center; border: 0px; border-radius: var(--devsite-button-border-radius,2px); box-shadow: none; color: var(--devsite-secondary-text-color); cursor: pointer; display: inline-block; font-style: normal; font-variant-ligatures: ; font-variant-caps: ; font-variant-numeric: ; font-variant-east-asian: ; font-weight: normal; font-stretch: ; font-size: 24px; font-family: &quot;Material Icons&quot;; height: 24px; letter-spacing: normal; line-height: 1; margin: 0px -40px 0px 0px; max-width: var(--devsite-button-max-width,none); min-width: 36px; outline: 0px; overflow: hidden; padding: 0px 8px; text-align: center; text-decoration: none; text-overflow: ellipsis; text-transform: none; transition: background-color 0.2s ease 0s, border 0.2s ease 0s, box-shadow 0.2s ease 0s; vertical-align: middle; white-space: nowrap; width: var(--devsite-button-width,auto); overflow-wrap: normal; direction: ltr; font-feature-settings: &quot;liga&quot;; -webkit-font-smoothing: antialiased; opacity: 1;"></button></h3><div class="api-level" style="box-sizing: inherit; margin: -40px 0px 0px; padding: 0px; float: right; font-size: smaller; color: rgb(32, 33, 36); font-family: Roboto, &quot;Noto Sans&quot;, &quot;Noto Sans JP&quot;, &quot;Noto Sans KR&quot;, &quot;Noto Naskh Arabic&quot;, &quot;Noto Sans Thai&quot;, &quot;Noto Sans Hebrew&quot;, &quot;Noto Sans Bengali&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: inherit; margin: 0px; padding: 0px;">Added in<span> </span><a href="https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels" style="box-sizing: inherit; color: rgb(34, 34, 34); outline: 0px; text-decoration: var(--devsite-link-text-decoration,none); word-break: break-word;">API level 1</a></div></div><devsite-code no-copy="" data-copy-event-label="" style="box-sizing: inherit; --devsite-code-background:#f8f9fa; --devsite-code-color:#37474f; --devsite-var-color:#d01884; --devsite-code-border:1px solid #e8eaed; --devsite-code-border-radius:8px; --devsite-code-margin:32px 0; border: var(--devsite-code-border,0); border-radius: var(--devsite-code-border-radius,0); clear: both; display: block; margin: var(--devsite-code-margin,16px 0); overflow: hidden; position: relative; direction: ltr !important; color: rgb(32, 33, 36); font-family: Roboto, &quot;Noto Sans&quot;, &quot;Noto Sans JP&quot;, &quot;Noto Sans KR&quot;, &quot;Noto Naskh Arabic&quot;, &quot;Noto Sans Thai&quot;, &quot;Noto Sans Hebrew&quot;, &quot;Noto Sans Bengali&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="devsite-code-buttons-container" role="group" aria-label="Aktionsschaltflächen" style="box-sizing: inherit; margin: 0px; padding: 0px; position: absolute; right: var(--devsite-code-buttons-container-right,0); top: 0px; z-index: 1;"><button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="Dunkles Codedesign" data-title="Dunkles Codedesign" style="box-sizing: border-box; appearance: none; background: 0px center; border: 0px; border-radius: 0px; box-shadow: none; color: rgb(32, 33, 36); cursor: pointer; display: inline; font-style: normal; font-variant-ligatures: ; font-variant-caps: ; font-variant-numeric: ; font-variant-east-asian: ; font-weight: normal; font-stretch: ; font-size: 18px; font-family: &quot;Material Icons&quot;; height: var(--devsite-code-button-size,24px); letter-spacing: normal; line-height: 1; margin: 0px; max-width: var(--devsite-button-max-width,none); min-width: auto; outline: 0px; overflow: hidden; padding: 0px; text-align: center; text-decoration: none; text-overflow: ellipsis; text-transform: none; transition: color 0.2s ease 0s; vertical-align: bottom; white-space: nowrap; width: var(--devsite-code-button-size,24px); overflow-wrap: normal; direction: ltr; font-feature-settings: &quot;liga&quot;; -webkit-font-smoothing: antialiased; -webkit-box-align: center; align-items: center; -webkit-box-pack: center; justify-content: center;"></button></div><pre class="api-signature no-pretty-print" translate="no" dir="ltr" is-upgraded="" style="box-sizing: inherit; background: transparent; color: inherit; font-style: ; font-variant-ligatures: ; font-variant-caps: ; font-variant-numeric: ; font-variant-east-asian: ; font-weight: normal; font-stretch: ; font-size: ; line-height: ; font-family: ; padding: 0px 0px 8px; direction: ltr !important; text-align: left !important; margin: 1em 0px; overflow-x: auto; position: relative; border: 0px;">public <a href="https://developer.android.com/reference/java/lang/String" style="box-sizing: inherit; color: var(--devsite-link-color); -webkit-font-smoothing: auto; font-weight: 700; outline: 0px; text-decoration: var(--devsite-link-text-decoration,none); word-break: break-word;">String</a> getUrl ()</pre></devsite-code><p style="box-sizing: inherit; margin: 16px 0px; padding: 0px; color: rgb(32, 33, 36); font-family: Roboto, &quot;Noto Sans&quot;, &quot;Noto Sans JP&quot;, &quot;Noto Sans KR&quot;, &quot;Noto Naskh Arabic&quot;, &quot;Noto Sans Thai&quot;, &quot;Noto Sans Hebrew&quot;, &quot;Noto Sans Bengali&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gets the URL for the current page. This is not always the same as the URL passed to WebViewClient.onPageStarted because although the load for that URL has begun, the current page may not have changed.</p><p style="box-sizing: inherit; margin: 16px 0px; padding: 0px; color: rgb(32, 33, 36); font-family: Roboto, &quot;Noto Sans&quot;, &quot;Noto Sans JP&quot;, &quot;Noto Sans KR&quot;, &quot;Noto Naskh Arabic&quot;, &quot;Noto Sans Thai&quot;, &quot;Noto Sans Hebrew&quot;, &quot;Noto Sans Bengali&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p><div class="devsite-table-wrapper" style="box-sizing: inherit; margin: var(--devsite-table-margin,16px 0); padding: 0px; overflow: auto; color: rgb(32, 33, 36); font-family: Roboto, &quot;Noto Sans&quot;, &quot;Noto Sans JP&quot;, &quot;Noto Sans KR&quot;, &quot;Noto Naskh Arabic&quot;, &quot;Noto Sans Thai&quot;, &quot;Noto Sans Hebrew&quot;, &quot;Noto Sans Bengali&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Returns
--
String | the URL for the current page or null if no page has been loaded

</div>

**Comment by scoute-dich** [comment]
In Ninjawebview initPreferences(String url) I made null-check for all url related settings. So this should be save now, whenn url returns null. All other settings should then be loaded.

`if (url != null) {
            CookieManager manager = CookieManager.getInstance();
            if (cookieHosts.isWhite(url) || sp.getBoolean("sp_cookies", true)) {
                manager.setAcceptCookie(true);
                manager.getCookie(url);
            }`

**Comment by scoute-dich** [comment]
If the problem persists in the latest version, please reopen or create a new issue.
