### ISSUE TITLE
Sometimes downloads are failing

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#651]
Tried to download Nina Warnapp as zip.
https://www.bbk.bund.de/DE/Warnung-Vorsorge/Warn-App-NINA/NINA-Download/nina-download_node.html

The file has about 30MB but download stops after a few MB and tells download complete.

No problem with Chrome or DuckDuckGo Android Browser.
It worked on my Android 10 device but fails on Android 6.0.1 and Android 11.
Clearing cache did not help.

Other - also large - downloads usually work.

Ideas?

**Comment by tusch001** [comment]
I'm on *Android 6.01*. About a week ago I downloaded Nina App with FOSS Browser 8.1.2 without problems. I think that is because on the website the app is provided as zip not as apk. This triggers my file manager to download the file - my default (compared to all other downloads which are handled by android download manager). 
File size is correct, installs correctly after renaming, I just tested it again. No problems on Android 6.01  

  
I tested it on *Android 9* where I am asked with which download manager I want to download - no problems with a modded Es file browser 3.2.5.5  from [here](https://github.com/3pehrbehroozi/es-FileExplorer-3) or the Download Navi from [f-droid](https://f-droid.org/packages/com.tachibana.downloader). 
But as in your case the Android Download Manager fails at 8 MB (when choosing Foss Browser as downloaf app for zip files my phone uses Android).


Maybe this is a problem of Android Download Manager and the created jession ID?

**Comment by woheller69** [comment]
Sometimes I get 4MB, sometimes 8MB, but not more...

Maybe something wrong in the intent we are sending to download manager?

**Comment by tusch001** [comment]
sorry - I'm no programmer. This is more your part. But I can help testing.

**Comment by tusch001** [comment]
Don't know if it's important: on the nina webpage of the Bundesamt it says that you need google play services not only to run the app but *also to download the app*.  

I have to admit that I downloaded the app but I only started it once because the app wants me to update play services which are deactivated on my phone.

**Comment by woheller69** [comment]
Play services are there, just did not want to use Play Store...

**Comment by tusch001** [comment]
I use [Evozi AP.k Downloader Web Page](https://apps.evozi.com/apk-downloader/) to download free google apps. Jusz paste the complete url or the apk name in the field, generate a download link and download any free google app :-)

**Comment by woheller69** [comment]
Are you sure you get the original unmodified apps there...? 
But that is not the problem. Of course it should also work with FOSS-Browser

**Comment by tusch001** [comment]
I've been using this website for 5+ years. At the beginning I did some checksums on maybe 10 - 15 apks. They were the same as google's. Haven't done that in years but I'm downloading there at least once a month with no complains so far (no unexpected web access by any downloaded app, ...).  
I'm no expert but I have made the decision to trust this site because sometimes you can get some apps only at google and I use microG but no signature spoofing. So ...  

You have to make your own decision.

**Comment by woheller69** [comment]
tried again. Now working without problems. So maybe their server was overloaded (?). But the question remains - why did it work then with Chrome / DuckDuckGo and fail with FOSS-Browser...

**Comment by woheller69** [comment]
Tried again. First time failed, second time worked, now it always fails
In all cases logcat says: DownloadManager: [XXX] Finished with status SUCCESS

DuckDuckGo Browser has no problems and I don't see a big difference in their way to start the downloads:
https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/browser/downloader/NetworkFileDownloader.kt

They are adding "User-Agent" as request header, but that does not make a difference (I tried it)

**Comment by scoute-dich** [comment]
I was on vacation a few days. I tested with Android 11 and always get different download sizes. Furthermore, I activated JavaScript, Cookies, DOM-Storage and disabled fingerprint-protecting. And Kotlin I've never learned (I'm too old).

**Comment by woheller69** [comment]
I don´t know Kotlin either, but as far as I can interpret it as a foreign language they are doing the same...
But there must be a difference !?

**Comment by scoute-dich** [comment]
Are they also use androids native webview?

**Comment by woheller69** [comment]
Tested again. Now it also fails with DuckDuckGo Browser and also with Chrome. So I think it is a server problem.
Probably we cannot expect more from a server run by our government...

**Comment by tusch001** [comment]
As I have now tested multiple times to download Nina app with other downloaders and never encounted problems I started testing it with foss browser again. This time I also used the `save as ..`. button. Multiple times with success, with and without Javascript enabled. At the moment I'm on a very slow network so I could even start the "normal" download by sharing the link to foss browser while the first download (with "save as") was still active. The second download failed even before the first download finished correctly.

Is there is a difference how the browser handles the two downloads or identifies the file type? Not that I'm an expert nor a programmer, but Android Download Manager shows

- different names for the download (domain name + time +.zip   `<--->` file name.zip)
- right from the start different file sizes (30+MB correctly for the zip-download / save as ...). The "normal" download shows always the wrong file size, right from the start (7-8 MB). And that is also the final file size.
- Also: the link / file name is different if you have Javascript enabled, maybe this is responsible for the different behaviour in other apps:
 - with JS: download_apk_nina.zipjsessonidXXXXXXXXXXXXXXXXXXXXX.live342  
   (no clear file ending)
 - without JS: download_apk_nina.zip

Maybe it would be worth to compare both methods with / without JS to find out what is the difference. I think the problem lies in the way how foss browser handels this (although I would not rule out that they have done some code changes on the server side). 

BTW in the past I sometimes encountered problems with downloading files but I didn't reported it due to the fact that I'm on old Android 6 and thought I should not bother you. So I'm not sure it is only this website.

Sorry long input, I hope get what I wanted to say. Thanks again for a great browser.

**Comment by woheller69** [comment]
but still it does not work with Chrome either at the moment. So I think we should not waste more time until there is another site with problems...
If there are more download problems we should collect them here

**Comment by scoute-dich** [comment]
Thanks for helping and the long post.

I'll compare both methods, when I find time. At the moment I do not know, when I've the time to code. I'm at home with three children (we still have summer vacations from school here). One of them is ill and my wife has to work...

Anyway: Your suggestion sounds good. I'll open a new issue, where we can collect future download problems, if the issue can't be solved in near future.

**Comment by tusch001** [comment]
another failed download:  
I activated Two-Factor-Athentication on github.com for my account. Github asked me to save the recovery codes as txt-files. This doesn't trigger my download manager, so the browser suggested Android Download Manager. No Success. Three failed downloads. The site needs javascript something I usually don't have activated while browsing the web.  

BTW: is it possible to make the user choose his / her own download manager in settings? I had the opportunity to set my download manager for zip files but I never got asked for other file types.

**Comment by woheller69** [comment]
On EU Digital Passenger Locator Form (dPLF) https://app.euplf.eu/#/user/login the download of the pdf file with the registration fails. The browser recognizes a pdf and offers to download. Then obviously download manager fails with error message

**Comment by tusch001** [comment]
[Base64 Image Encoder](https://products.aspose.app/ocr/de/img-to-base64) - Download generated txt-String from png image fails immediately with message:
```
Can only download HTTP/HTTPS URIs:
blob:https://products.aspose.app/hex-value-groups
```
(replace hexvalues with your image - id)  

In other apps this resolves into a https:// link (without blob:) to a downloadable text file which the additional ending `.txt`

**Comment by tusch001** [comment]
Just found out that on a website where I have access to the CMS the downloads are also failing. No Javascript involved. Files are uploaded by registered users, www has unrestricted access for download. No problems on major desktop browsers (Android below).

Serverside:
CMS Drupal. lets encrypt ssl certificate.

Due to security there is no direct access to the download file on the server. Instead the CMS creates a different link for display. The download request results in a check for file access rights and then the file is served.

HTML is like this:
```
<span class="file file--mime-application-pdf file--application-pdf">
  <a href="https://example.com/system/files/media/downloads/public/filename.pdf" type="application/pdf" title="filename.pdf">
    descriptive filename
  </a>
</span>
```
behaviour on clientside:
- desktop firefox opens pdf in tab, user can download from there
- ff android asks to choose app for download and - if chosen - downloads file correctly
- duckduckgo android: it takes quite a while (5 s) then a confirnation dialogue asks for permission to save file as `system.pdf` (this wrong filename get all files!) - download fails and app complains that android download manager is deactivated (it is not)
- the app VT view source failes with message: 'Sorry, the SSL certificate seemed not to be trusted. For security reasons provided url cannot be fetched. java.security.cert.CertPathValidatorException: Trust anchor for certification path not found' (WTF - there is nothing wrong with the certificate)

Summary:
Somewhere something goes very wrong. But I have no idea where. Will do some testing on the server side and report back.

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/7784046/app-debug.apk.zip)
Hi, this is an old and annoying issue. I had problems to download some files from G-Drive. The attached apk solves this issues for me. If someone wants to test some downloads, he can report back.
