### ISSUE TITLE
'return' key doesn't work

### ISSUE THREAD

**Issue by iynere** [scoute-dich/browser#66]
love this browser !! url bar on the bottom is a great innovation for mobile browsing.

expected browser behavior is for the 'return' key to tell the browser to navigate to what you've just typed, but here it just closes the keyboard & u still need to click the right arrow button to actually go. thanks !!

**Comment by scoute-dich** [comment]
I think you're at version 4.+. The current version is 5.1. Since version 5 I use Ninja Browser as the base for Browser. In the new version this is fixed.

F-Droid has build errors last time, so the last updates aren't available there. I also didn't publish an update on PlayStore yet. But of you want, you can download there largest version in the releases section as apk-file.

**Comment by scoute-dich** [comment]
Works in v5+
