### ISSUE TITLE
Userscripts

### ISSUE THREAD

**Issue by jmthackett** [scoute-dich/browser#664]
Hey,

I really like this project for its simplicity and was wondering if the idea of userscripts would be of interest. These would have full access to the DOM and load at the end of a page load. They can be used to switch off annoying popups, do dark modes for sites that don't have them, add or remove social buttons etc.

At a glance, it looks possible on the basis of this SO post:

https://stackoverflow.com/questions/2219074/in-android-webview-am-i-able-to-modify-a-webpages-dom

Changing this to look for mysite.com.user.js would let me (eg) bypass GDPR blocks on that file. What I'm not sure of is how to sensibly get the script in place. I guess copy pasting would be one approach.

Is this the kind of thing you'd want in FOSS Browser?

**Comment by woheller69** [comment]
I don't know if Faun wants to have this feature, but I think it would be easy to implement. It works the same way as the stuff for preventing fingerprinting, which I implemented recently.
We could take a string, editable in settings, and send it through view.evaluateJavascript in onPageFinished of NinjaWebViewClient.
Or better 3 editable strings executed at onPageStarted, onLoadResource, an onPageFinished

**Comment by woheller69** [comment]
Here is something to play with. Rename file to .apk and install.

In settings you have 3 options to switch on an add a script, e.g.

        alert('Test');

[app-debug.zip](https://github.com/scoute-dich/browser/files/7072232/app-debug.zip)

**Comment by scoute-dich** [comment]
Could we block also these a annoying "Cookie-Popups", displayed in the EU?

**Comment by scoute-dich** [comment]
Another question: Do userscipts or fingerprint protection also work with JavaScript disabled?

**Comment by woheller69** [comment]
with the right script we could automatically answer them, but every site is different or there are at least quite a few systems in use...
So I think for the moment the answer is no.
Maybe in future based on specifications like this, which are being discussed.
https://www.dataprotectioncontrol.org/spec/

**Comment by woheller69** [comment]
Userscripts and fingerprint protection need javascript. But without Javascript most fingerprinting methods are blocked because they also rely on Javascript.

**Comment by tusch001** [comment]
Maybe you could offer the user a tool to select the gdpr box and other annoying elements. The container based on the nearest outer id attribute, maybe with inner child element (domain/path#id  > div > div), could be hidden with the user script or with css when reloading / revisiting the page. The firefox addon element blocker does it this way. 
I think we need a human to decide what to hide. The code is - until future regulations - not sufficient defined for automation. Apart from searching for ids as 'cookie*', 'ad*', 'consent*'.

**Comment by tusch001** [comment]
Even without activated javascript there are far too many elements on some websites that need to be blocked for the pages to be useful (hello amazon)

**Comment by jmthackett** [comment]
I'd point out that with a generic per-site userscript ability in the browser, there is the option to take this out of the hands of the browser devs and share scripts. As such it maybe isn't that useful to talk about what scripts we'd like, but it is good to hear that people do actually want them.

On August 30, 2021 9:55:19 PM UTC, tusch001 ***@***.***> wrote:
>Even without activated javascript there are far too many elements on
>some websites that need to be blocked for the pages to be useful (hello
>amazon)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/browser/issues/664#issuecomment-908728033

-- Sent from /e/ Mail.

**Comment by tusch001** [comment]
I don't want to reinvent the wheel and create my own blocking lists. There is a firefox addon called 'I dont care about cookies'. It does a pretty good job in hiding unwanted elements. We can't use FF addon system but maybe we could use the authors lists for blocking gdpr content and adapt it to this browser. The same way the hosts file is used and updated for blocking ads / third patry content but on the level of html / dom?

**Comment by woheller69** [comment]
as far as I understand it  'I dont care about cookies' accepts all cookies, and that is the opposite of my preference...

**Comment by woheller69** [comment]
has anyone already tried a script using the app-debug.apk above?

Via window.location.href you should be able to access the current URL from Javascript, so you can even run site specific code

**Comment by jmthackett** [comment]
Not yet, sorry, I'm going to try it tonight after work though.

On August 31, 2021 5:17:07 AM UTC, woheller69 ***@***.***> wrote:
>has anyone already tried a script using the app-debug.apk above?
>
>Via window.location.href you should be able to access the current URL
>from Javascript, so you can even run site specific code
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/browser/issues/664#issuecomment-908906910

-- Sent from /e/ Mail.

**Comment by tusch001** [comment]
@woheller69: "has anyone already tried a script using the app-debug.apk above?"
I hacked some lines of code for a user.js (haven't used javascript for 20 years, so very old school procedural code). I just don't know if

- I have some programming errors 
- placed the file wrong
- it's in general not working on Android 6.01

I started the debug-browser, activated 'User script onLoadResource' and put in the path to my file (`/storage/emulated/0/Download/user.js)`. The browser should be able to read that file, right? I get a microsecond (ok maybe 0.05 s) white blink on top of the page. Then it's gone and the normal page is shown. Nothing more. (even `alert ('test'); or `setTimeout ( alert('test'), 5000);` doesn't work). Do I need something like onLoad call function...? My shortly hacked script was supposed to hide the big cookie element on 'https://www.amazon.de'. Not working.

**Comment by woheller69** [comment]
no, the input field is not for the path. It is for the script itself.

e.g put 

         alert('Test');

into the field for onPageStarted and you will get a popup when loading starts.

**Comment by tusch001** [comment]
`document.getElementById('sp-cc').style.display = 'none';` hides the cookie consent form on https://www.amazon.de.  
So original question of this issue is answered. Yes user scripts do work.  
  
But:  
they only do work, if JS is activated. Which prompts my next question: If you want to go along an block elements like gdpr, ... and don't have javascript activated: Can we inject css code as a file? I'm thinking about 20 year old ways of having a user.css that supersedes with the right css code any web site specific display, e.g. for visually impaired users. We could use this system to block elements in css. I just don't know if it is possible to have a custom.css file, although I would assume that WebView supports this.

**Comment by woheller69** [comment]
I don't think that is possible without JS. But maybe someone else has an idea how to do it ...?

**Comment by tusch001** [comment]
Since I'm still on a beginner level with java and OOP, I have a stupid question: how do you process the downloaded page.html before displaying it? (I really don't know). Is it possible to have the html file, go to EOF, go back 7 characters (length of '</html>' and put extra characters in there like `<link rel="stylesheet" media="all" href="https://github.com/scoute-dich/browser/path/to/user.css" /> `? And the tell java to do the display thing.

**Comment by woheller69** [comment]
maybe injecting css works via shouldInterceptRequest but I don't have a vlue about that...

https://stackoverflow.com/questions/8273991/webview-shouldinterceptrequest-example

**Comment by woheller69** [comment]
should we add the possibility for user Javascript as already implemented to the project? Then I can make a pull request.

**Comment by tusch001** [comment]
I have found here ([Rendering HTML in a WebView with custom CSS](https://stackoverflow.com/questions/4950729/rendering-html-in-a-webview-with-custom-css)) a reference to [this documentation on Android Developers](https://developer.android.com/reference/android/webkit/WebView.html). Can you do some magic with "Constructs a new WebView with layout parameters and a default style." (about a third down the page)

**Comment by woheller69** [comment]
that has nothing to do with the content displayed inside the webview

**Comment by jmthackett** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/src/js/contentScript.js

If I'm understanding correctly, something like this should be able to run as a userscript. Albeit this one comes from a Firefox add-on the principle seems the same. I didn't get chance to test tonight though but will try to find time asap.

On August 31, 2021 7:56:41 PM UTC, woheller69 ***@***.***> wrote:
>that has nothing to do with the content displayed inside the webview
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/browser/issues/664#issuecomment-909570692

-- Sent from /e/ Mail.

**Comment by tusch001** [comment]
@jmthackett I did test the referenced script bei passing the content directly into the field. I did only test some english websites. As far as I can tell the script works but most of the sites I visited have changed their code and the css selectors in the script are outdated. They don't work any more.  

I  replaced for testing on the [Financial Times](ft.com) the selector `.o-banner__outer` by `.o-cookie-message__outer` and then the cookie message was gone. Yes the script works but it also shows the difficulties with maintaining scripts like these: they are rapidly outdated.  

In your initial post you stated to use this to block annoying elements (I'm all for that). So I hope if you don't mind stating my opinion:

- for this to work JS needs to be activated all the time. In my opinion this renders the button `deactivate JS` useless
- the script just references ~ 200 domains, each has 1 - 3 contents to be blocked. And as far as I can tell these are only news websites. No ebay, amazon, ... in the list. You name it. On my 5 yr old phone with 3 GB RAM and snapdragon 617 chip it took about 2 s to hide the box. And I already had a feeling of this being too long. Browsing the web I'm not that tolerant with delays. Yes the code could be optimized, but I think there is a limited number of entries.

Then there is the task of creating these lists:
- the easiest solution would be to pay a company to maintain this blocking list (~ 5$ are typical monthly fees): I don't see users of this minimalistic app go this way.
- so we have to maintain these lists ourselves - either as a community task (remember limited entriys for 100+ languages) or each user has to do it himself. Then there must be a tool for the user to select the element within the displayed webpage (this part is easy). The tool must also support to find a parent node while displaying the code at the same time in a small 5 - 6 " screen. Why? Because some elements hide the content by making the background dark and have the consent form in the center better visible. Identifying this parent node correctly is not so easy any more. And if this parent node doesn't have an id or maybe not even a class name the user must be knowledgable about css selector rules.  

Who is going to do this work? How many in the community can we trust to do this correctly? And if you are done let's say with 100 sites start over again? Can we use some existing scripts from popular FF Addons like AdBlocker or UBlock Origin and ajust them? But where would we get a list for gdpr content elements?

This is not a simple project. This is pandorras box.

**Comment by tusch001** [comment]
@woheller69: 
Can you rethink about the UI. A field to paste code into is not the best solution when there are hundreds of lines of code (774 lines of code in jmthackets script). Maybe load the code from a file?

**Comment by jmthackett** [comment]
Loading code from a URL (with a refresh button) would be amazing. Even better for loading an arbitrary number of scripts in order. I'd point mine at the script above, others could choose something more to their liking, with the UI being a bit like subscribing to the various ad blocking lists.

On August 31, 2021 11:19:20 PM UTC, tusch001 ***@***.***> wrote:
***@***.***: 
>Can you rethink about the UI. A field to paste code into is not the
>best solution when there are hundreds of lines of code (774 lines of
>code in jmthackets script). Maybe load the code from a file?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/browser/issues/664#issuecomment-909721565

-- Sent from /e/ Mail.

**Comment by woheller69** [comment]
I would like to keep the interface as simple as it is. 
But it should not be too complicated to write some Javascript code that executes JS from one or several URLs, right?

**Comment by jmthackett** [comment]
It looks like that is possible, according to [this blog post.](https://aaronsmith.online/easily-load-an-external-script-using-javascript/)

```
const myScript = document.createElement('script')
myScript.src = 'https://raw.githubusercontent.com/iamadamdev/bypass-paywalls-chrome/master/src/js/contentScript.js'
document.head.append(myScript)
```

That'd be fine for me. It might annoy github but personally I can always mirror and it is probably better to do so from a security POV anyway.

**Comment by tusch001** [comment]
@woheller69 that's exactly what I wanted to say. Nobody has the time to do it. @scoute-dich asked if it is possible to block gdpr. Yes in theory. But not in any long term maintainable way.

**Comment by woheller69** [comment]
That is what I also said. At the moment it is too complicated. It may make sense if there is a generic specification for that in future.
Nevertheless I think it makes sense to add the possibility for user scripts as implemented to the project.

**Comment by Zehra** [comment]
I like the idea of userscripts, but it seems to be there is a lot of tricky parts with them.

The following bullet points are for points of reference:
* Adding Userscript support does not seem to be that difficult.
* It does not seem that difficult to write userscripts.
* It seems tedious to write them on mobile devices.
* It seems most websites have a mobile and desktop version.
* Most websites have complicated/lengthy HTML, CSS and JavaScript.
* It seems to be a good feature, but with risk of feature creep.
---
Now based off of this, I make the following observations:

If it's tedious to write userscripts on mobile, we can add in lots of templates, frameworks, samples..etc, but it seems to be a lot of work to add it in as a nice feature or to select/use them easily. (Either in this browser or in another app, text editor, IDE.)

GreaseMonkey scripts do not seem as a viable drop-in solution, as most websites have mobile and desktop versions.

Since most websites have complicated and lengthy HTML and CSS, frequently with multiple CSS files, it would make viewing pages/sources time consuming and non-practical.

A desktop could view the pages and allow remote editing/adding of userscripts, but it does not seem really workable.

---

Also the goal of userscripts seems to be lost here...
* Is mostly for blocking/removing elements?
If mostly for removing cookie templates and related, extensions like uBlock Origin are better suited for this. (1-2 seconds to remove cookie notice vs time to write/modify userscript.)
* Is it mostly for adding in features/tools?
If so, it seems this would be better suited for another tool/application, since doing what is limited to JavaScript without API features is limited and not really well suited for this.(Unless some API is added which might be more trouble than it is worth.)

**Comment by Zehra** [comment]
My worries of feature creep have been addressed.

**Comment by scoute-dich** [comment]
Hi,

I merged the pull request. I'll test it. And next week I'll release an update. At the moment I'm not very active, since there are some private things to clear.

Anyway thanks to you all for discussing. I red all comments.

Sunny greetings!

**Comment by sjehuda** [comment]
> My worries of feature creep have been addressed.

Put it under "Extensions" or "Advanced".

---

I think this should be of high priority.

With the newer additions of javascript in recent years, there are plenty of userscripts that can do just as much as an most of the extension addons available.

The main "advantage" that other web browsers used to provide, is installing extensions.
