### ISSUE TITLE
Be able to remember night mode per site

### ISSUE THREAD

**Issue by KeronCyst** [scoute-dich/browser#669]
8.2 on LG G6 running Android 8.0.0:

I found at least one website whose text becomes nearly invisible when night mode is attempted on it. So it would be really helpful if we could make a list of domains to add to an exceptions list, for the browser to remember.

Alternatively, this was the website, if any fix can be done for it: https://lgbta.wikia.org (pretty much any article on here)

**Comment by woheller69** [comment]
for me this site works well in day and night mode

**Comment by KeronCyst** [comment]
I'm not sure of what's going on because this is what it looks like when it's fully loaded at night:

![Capture+_2021-09-06-16-44-08](https://user-images.githubusercontent.com/13827055/132262103-fb635f42-a5f6-4573-af9c-b99fe6a50e22.png)

Day:

![Capture+_2021-09-06-16-45-38](https://user-images.githubusercontent.com/13827055/132262109-a40c9665-3c81-401d-b6ef-1ff37ff06a7a.png)

**Comment by tusch001** [comment]
There are more pages that are not displayed with correct colours. I think it depends either on the html (div tag vs p tag) or on the css behind. On my own webpage there is a mismatch: some containers get colours changed others not. My css template is completely hand made, I could investigate further.  
  
@devs If it is something to be fixed by the browser I can spend some time to find what triggers the different behaviour. I'm just not sure if there is an easy fix.

**Comment by scoute-dich** [comment]
Hi,

with the next update, night mode will be saved for entries saved on startsite, bookmarks or history. The items on startsite or bookmark list can be edited.

> If it is something to be fixed by the browser I can spend some time to find what triggers the different behaviour. I'm just not sure if there is an easy fix.

Thanks for wanting to help. I have also some websites where nightmode is not working correctly. I believe these are website issues (if you want to call it that way).

So with this feature added, I'll close this issue.
