### ISSUE TITLE
Browser is not compatible with Xfinity Stream

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#732]

**Comment by scoute-dich** [comment]
![Screenshot_20211207-210227_FOSS Browser](https://user-images.githubusercontent.com/3949944/145098130-c9db9c57-8546-4b4d-a61d-312a84830152.png)
For me the site seems to work. Please describe the problem. Are you using latest version of FOSS Browser? Are you using latest webview? Which Android version?

**Comment by scoute-dich** [comment]
![Screenshot_20211207-210517_FOSS Browser](https://user-images.githubusercontent.com/3949944/145098494-8da0e92b-ab2d-4c05-9df8-aa443ffa887d.png)
These are my current profile settings.

**Comment by Kita2345** [comment]
Version 8.4.1 from F-Droid
Webview 96.0.4664.45
Android 7.1

**Comment by scoute-dich** [comment]
I can not test playing videos, because I have no account. Have you tried disabling fingerprint protection? Some websites don't display the content correct, when disabled.

**Comment by CaptainFrosty** [comment]
I don't have Xfinity, but I have Spectrum which is similar, and if it's anything like my cable company's site for streaming TV to the browser it won't work because it requires support for Widevine DRM which I assume this browser does not have as it is extremely proprietary.

**Comment by CaptainFrosty** [comment]
In fact, I somehow managed to get one of my browsers on my PC banned from the site... I can only guess because of the way it was configured: anti-FP, FPI or something like that. 

I can still use other browsers, but if I use that one I get a message in the reply header about my device being revoked. I did a full wipe: cookies, cache, DOM, indexedDB, session. Even created  a fresh profile and spoofed my UA. They still manage to identify that browser. They are fingerprinting something that the browser's anti-FP setting doesn't protect it seems. Wish I knew what.

So be careful messing around with Widevine. Can't access something I pay for with the browser I wish to use. I have to keep another, less secure browser around when I'd rather not. Something tells me the Spectrum customer service would be a waste of time. I thought about emailing Google to see if they'd tell me precisely what in the connection angers Widevine so much, but they'd probably just give me the run-around. DRM, gotta love it.

**Comment by scoute-dich** [comment]
Widevine support seems to depend on your system and your WebView. So there odd nothing i can do. Sorry.

**Comment by CaptainFrosty** [comment]
@Kita2345 

After some more investigation I found it was likely the Navigator API that was allowing them to identify my browser. Same for Amazon Prime denying me HD for not using regular Firefox. The extension CanvasBlocker can spoof your Navigator to Firefox 95 on desktop at least. This fixed my issues. Also you can't use a VPN or modify your IP address to get cable TV services.
