### ISSUE TITLE
Certificate not trusted

### ISSUE THREAD

**Issue by Tealk** [scoute-dich/browser#856]
Hello

I get with almost every web page the certificate message displayed which I then have to confirm several times (message overlaps 4-6 times)

![Screenshot_20220126-002457.png](https://user-images.githubusercontent.com/12276250/151076913-f9a8d00b-fafe-4662-86ce-15ee27f39c1f.png)

Pixel6
CalyxOS (Android12)

**Comment by scoute-dich** [comment]
I can not confirm this. "Heise online" is displayed without any problems here. Perhaps it's a network issue or a problem with your installed webview. Any other hints?

**Comment by ndr1224** [comment]
@scoute-dich 
https://www.dnsleaktest.com/

You can produce error in this website while doing test.

**Comment by Tealk** [comment]
I have now narrowed it down to the DNS server from NextDNS
but with dnsleaktest this also always comes no matter which dns server

**Comment by flocke** [comment]
Are you by any chance using AdAway (or something similar) on your phone?
I had the same issue and it turned out to be caused by the "Local web server" setting in AdAway. That server is using a self signed certificate, which is not trusted by Android. Disabling the "Local web server" in AdAway solved it for me.

**Comment by scoute-dich** [comment]
So I'll close this, since it is not FOSS Browser related. If you have further problems, please reopen.
