### ISSUE TITLE
Image download fails from pixiv

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#921]
https://www.pixiv.net/en/artworks/83953383

Android version
Android 9

**Comment by tusch001** [comment]
Maybe something similiar to #920 to prevent people from downloading images?
Site is also only visible with activated JS. When I load the page in firefox I can see the picture loading. Then after approx 0.5 s the page is reloaded. If you interupt this reloading of the page in firefox there is no image but an error message with a link to reload the picture (not a partially loaded image). So I think there is also some JS active. 
When the page is fully loaded and the image is clicked I'm asked to open an account, not to download a jpg file. This `<div>` is also on top of the image.

Just guessing: not something that can be fixed in the browser?

**Comment by scoute-dich** [comment]
> Just guessing: not something that can be fixed in the browser?
