### ISSUE TITLE
Update FOSS Browser on Google Play

### ISSUE THREAD

**Issue by ghost** [scoute-dich/browser#927]
It was last updated on July 17, 2021 and this version 8.1.2 requires Android 5.0 and up, unlike the current version 9.2 requires Android 7.0 or newer.
https://play.google.com/store/apps/details?id=de.foss.browser

**Comment by ksapp-dell** [comment]
The latest version is on F-droid for download released some days ago.

**Comment by tusch001** [comment]
Or here under the release link. Be aware that there are different app signatures. You need to save your settings first and then uninstall the google version before installing the version from other sources.

**Comment by scoute-dich** [comment]
The truth is, that I deleted my Google developer account. It is a pain to get things done the way Google wants. And if you don't play with their rules you can not update your app. Or in the worst case, they remove the app from PlayStore.

Using the storage permission for the backup was the thing Google complained. There were some other things in the past. And since I'm doing all this in my free time, I decided to drop PlayStore support.

In this report (German language) you have other popular examples (FairMail, Total Commander):

https://www.heise.de/news/App-FairEmail-aus-dem-Google-Play-Store-entfernt-7101949.htmlhttps://www.heise.de/news/App-FairEmail-aus-dem-Google-Play-Store-entfernt-7101949.html

**Comment by woheller69** [comment]
can get difficult on F-Droid too. Recently they did not merge my new app due to storage permission for backup. I more or less copied that part from FOSS Browser...
In the end I changed it by using SAF and creating a Zip.
Just in case, here is the commit.

https://github.com/woheller69/audiometry/commit/ef4ca59259573685451a67595b9e0a40c45bb4c5
