### ISSUE TITLE
Is there an accessible config file?

### ISSUE THREAD

**Issue by LarkPm** [scoute-dich/browser#954]
i am new to this github site, but i will explain what i have.

My phone's android version: 6.0
Foss browser version: 8.1.2 (Google Play release)

Issue: i have incorrectly set an error address on Favorite Page/Starting Page. i cannot change the settings since the app crashes before i can access it.

Request: Is there a config file that can be accessed using the file manager so i can fix the favorite page?

Alternative request: If there is no accessible config file, can i recover the saved bookmarks on this version?

**Comment by tusch001** [comment]
> can i recover the saved bookmarks on this version?

Goto SDcard - Documents - browser_backup.
Depending on browser version the file had different names. Look for something like

- export_Bookmark.html
- list_bookmarks.html
- export_bookmark_list.html

I think browser version 8.4.1 here on github release page is the last that works with Android 6. It has a different signature so you need to uninstall google version first. Perhaps your problem is gone in this github version.

MAKE SURE YOU SAVE THE ABOVE MENTIONED FOLDER BEFORE UNINSTALLING THE BROWSER (the complete folder `browser_backup`).
Then install version 8.4.1, restore backup folder and import the settings in browser.

If that is not working:

I don't think there is a config file (not 100% sure, I'm no programmer) but I think the settings are exported as SQlite database (file database.db in Documents - browser_backup). Maybe you can edit that database with an SQlite editor? There was even some android app for this but I can't remember its name. Was some years ago on google.

**Comment by LarkPm** [comment]
Thank you for sharing your insight, unfortunately i have not exported my bookmarks and settings beforehand.

The accessing the root method seems too difficult on my part. i have no formal knowledge on it, even on quick search it seemed too risky and unsafe that could compromise my device.

Fortunately, i have found a workaround solution to the starting page/favorite page mishap.

Solutions: a) Open any bookmark exported in your device, then set it "Open with: Foss Browser"

b) Use a secondary browser (either native, or a downloaded one), go to a website and use "Open link with: Foss browser".

It will override the starting page/favorite page with that new link, preventing the invalid address crash loop. From there, you can safely correct the address on starting page.

i hope there is a override code that checks the starting page for any invalid input. If it is invalid it will just redirect itself to open with a blank tab (start page with about:blank) instead.

Postnote: i just have a high probability to break stuff up, but i am enjoying this Foss browser despite that im using an older version.

Good thing i had a secondary browser to complement any feature that Foss browser lacks (or features that i cannot workaround with).

**Comment by tusch001** [comment]
@scoute-dich: does actual release android 6 again?

**Comment by scoute-dich** [comment]
No, sorry.
